version: "3"
services:
  web:
    image: registry.cn-beijing.aliyuncs.com/qinyujia-test/java-web-demo
    labels:
      aliyun.probe.url: 'tcp://container:8080'
      aliyun.probe.initial_delay_seconds: '10'
      aliyun.routing.port_8080: codepipeline/demo
