web:
  image: registry.cn-hangzhou.aliyuncs.com/codepipeline/java-demo
  restart: always
  labels:
    aliyun.probe.url: 'tcp://container:8080'
    aliyun.probe.initial_delay_seconds: '10'
    aliyun.routing.port_8080: codepipeline/demo
